// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/NodeReflector.proto

package noderelayclient;

public final class NodeReflector {
  private NodeReflector() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:noderelayclient.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string secret = 1;</code>
     */
    java.lang.String getSecret();
    /**
     * <code>string secret = 1;</code>
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>string metadata = 2;</code>
     */
    java.lang.String getMetadata();
    /**
     * <code>string metadata = 2;</code>
     */
    com.google.protobuf.ByteString
        getMetadataBytes();

    /**
     * <code>string userdata = 3;</code>
     */
    java.lang.String getUserdata();
    /**
     * <code>string userdata = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserdataBytes();

    /**
     * <code>string namespace = 4;</code>
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 4;</code>
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string pod = 5;</code>
     */
    java.lang.String getPod();
    /**
     * <code>string pod = 5;</code>
     */
    com.google.protobuf.ByteString
        getPodBytes();
  }
  /**
   * Protobuf type {@code noderelayclient.Node}
   */
  public  static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:noderelayclient.Node)
      NodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      secret_ = "";
      metadata_ = "";
      userdata_ = "";
      namespace_ = "";
      pod_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              secret_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              metadata_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userdata_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              pod_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noderelayclient.NodeReflector.internal_static_noderelayclient_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noderelayclient.NodeReflector.internal_static_noderelayclient_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              noderelayclient.NodeReflector.Node.class, noderelayclient.NodeReflector.Node.Builder.class);
    }

    public static final int SECRET_FIELD_NUMBER = 1;
    private volatile java.lang.Object secret_;
    /**
     * <code>string secret = 1;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      }
    }
    /**
     * <code>string secret = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METADATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object metadata_;
    /**
     * <code>string metadata = 2;</code>
     */
    public java.lang.String getMetadata() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadata_ = s;
        return s;
      }
    }
    /**
     * <code>string metadata = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMetadataBytes() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERDATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object userdata_;
    /**
     * <code>string userdata = 3;</code>
     */
    public java.lang.String getUserdata() {
      java.lang.Object ref = userdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userdata_ = s;
        return s;
      }
    }
    /**
     * <code>string userdata = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserdataBytes() {
      java.lang.Object ref = userdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAMESPACE_FIELD_NUMBER = 4;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 4;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POD_FIELD_NUMBER = 5;
    private volatile java.lang.Object pod_;
    /**
     * <code>string pod = 5;</code>
     */
    public java.lang.String getPod() {
      java.lang.Object ref = pod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pod_ = s;
        return s;
      }
    }
    /**
     * <code>string pod = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPodBytes() {
      java.lang.Object ref = pod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, secret_);
      }
      if (!getMetadataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metadata_);
      }
      if (!getUserdataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userdata_);
      }
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, namespace_);
      }
      if (!getPodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, pod_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, secret_);
      }
      if (!getMetadataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metadata_);
      }
      if (!getUserdataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userdata_);
      }
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, namespace_);
      }
      if (!getPodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, pod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof noderelayclient.NodeReflector.Node)) {
        return super.equals(obj);
      }
      noderelayclient.NodeReflector.Node other = (noderelayclient.NodeReflector.Node) obj;

      boolean result = true;
      result = result && getSecret()
          .equals(other.getSecret());
      result = result && getMetadata()
          .equals(other.getMetadata());
      result = result && getUserdata()
          .equals(other.getUserdata());
      result = result && getNamespace()
          .equals(other.getNamespace());
      result = result && getPod()
          .equals(other.getPod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SECRET_FIELD_NUMBER;
      hash = (53 * hash) + getSecret().hashCode();
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
      hash = (37 * hash) + USERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getUserdata().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + POD_FIELD_NUMBER;
      hash = (53 * hash) + getPod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static noderelayclient.NodeReflector.Node parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static noderelayclient.NodeReflector.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelayclient.NodeReflector.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(noderelayclient.NodeReflector.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code noderelayclient.Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:noderelayclient.Node)
        noderelayclient.NodeReflector.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return noderelayclient.NodeReflector.internal_static_noderelayclient_Node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return noderelayclient.NodeReflector.internal_static_noderelayclient_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                noderelayclient.NodeReflector.Node.class, noderelayclient.NodeReflector.Node.Builder.class);
      }

      // Construct using noderelayclient.NodeReflector.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        secret_ = "";

        metadata_ = "";

        userdata_ = "";

        namespace_ = "";

        pod_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noderelayclient.NodeReflector.internal_static_noderelayclient_Node_descriptor;
      }

      @java.lang.Override
      public noderelayclient.NodeReflector.Node getDefaultInstanceForType() {
        return noderelayclient.NodeReflector.Node.getDefaultInstance();
      }

      @java.lang.Override
      public noderelayclient.NodeReflector.Node build() {
        noderelayclient.NodeReflector.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public noderelayclient.NodeReflector.Node buildPartial() {
        noderelayclient.NodeReflector.Node result = new noderelayclient.NodeReflector.Node(this);
        result.secret_ = secret_;
        result.metadata_ = metadata_;
        result.userdata_ = userdata_;
        result.namespace_ = namespace_;
        result.pod_ = pod_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noderelayclient.NodeReflector.Node) {
          return mergeFrom((noderelayclient.NodeReflector.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(noderelayclient.NodeReflector.Node other) {
        if (other == noderelayclient.NodeReflector.Node.getDefaultInstance()) return this;
        if (!other.getSecret().isEmpty()) {
          secret_ = other.secret_;
          onChanged();
        }
        if (!other.getMetadata().isEmpty()) {
          metadata_ = other.metadata_;
          onChanged();
        }
        if (!other.getUserdata().isEmpty()) {
          userdata_ = other.userdata_;
          onChanged();
        }
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getPod().isEmpty()) {
          pod_ = other.pod_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        noderelayclient.NodeReflector.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (noderelayclient.NodeReflector.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object secret_ = "";
      /**
       * <code>string secret = 1;</code>
       */
      public java.lang.String getSecret() {
        java.lang.Object ref = secret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        java.lang.Object ref = secret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder clearSecret() {
        
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secret_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object metadata_ = "";
      /**
       * <code>string metadata = 2;</code>
       */
      public java.lang.String getMetadata() {
        java.lang.Object ref = metadata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metadata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMetadataBytes() {
        java.lang.Object ref = metadata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metadata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder setMetadata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metadata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder clearMetadata() {
        
        metadata_ = getDefaultInstance().getMetadata();
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder setMetadataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metadata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userdata_ = "";
      /**
       * <code>string userdata = 3;</code>
       */
      public java.lang.String getUserdata() {
        java.lang.Object ref = userdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserdataBytes() {
        java.lang.Object ref = userdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public Builder setUserdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public Builder clearUserdata() {
        
        userdata_ = getDefaultInstance().getUserdata();
        onChanged();
        return this;
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public Builder setUserdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userdata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 4;</code>
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pod_ = "";
      /**
       * <code>string pod = 5;</code>
       */
      public java.lang.String getPod() {
        java.lang.Object ref = pod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pod = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPodBytes() {
        java.lang.Object ref = pod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pod = 5;</code>
       */
      public Builder setPod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pod = 5;</code>
       */
      public Builder clearPod() {
        
        pod_ = getDefaultInstance().getPod();
        onChanged();
        return this;
      }
      /**
       * <code>string pod = 5;</code>
       */
      public Builder setPodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pod_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:noderelayclient.Node)
    }

    // @@protoc_insertion_point(class_scope:noderelayclient.Node)
    private static final noderelayclient.NodeReflector.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new noderelayclient.NodeReflector.Node();
    }

    public static noderelayclient.NodeReflector.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      @java.lang.Override
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public noderelayclient.NodeReflector.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeFilterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:noderelayclient.NodeFilter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string secret = 1;</code>
     */
    java.lang.String getSecret();
    /**
     * <code>string secret = 1;</code>
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>string matchMetadata = 2;</code>
     */
    java.lang.String getMatchMetadata();
    /**
     * <code>string matchMetadata = 2;</code>
     */
    com.google.protobuf.ByteString
        getMatchMetadataBytes();

    /**
     * <code>string negateMetadata = 3;</code>
     */
    java.lang.String getNegateMetadata();
    /**
     * <code>string negateMetadata = 3;</code>
     */
    com.google.protobuf.ByteString
        getNegateMetadataBytes();

    /**
     * <code>string matchUserdata = 4;</code>
     */
    java.lang.String getMatchUserdata();
    /**
     * <code>string matchUserdata = 4;</code>
     */
    com.google.protobuf.ByteString
        getMatchUserdataBytes();

    /**
     * <code>string negateUserdata = 5;</code>
     */
    java.lang.String getNegateUserdata();
    /**
     * <code>string negateUserdata = 5;</code>
     */
    com.google.protobuf.ByteString
        getNegateUserdataBytes();

    /**
     * <code>string matchNamespace = 6;</code>
     */
    java.lang.String getMatchNamespace();
    /**
     * <code>string matchNamespace = 6;</code>
     */
    com.google.protobuf.ByteString
        getMatchNamespaceBytes();

    /**
     * <code>string negateNamespace = 7;</code>
     */
    java.lang.String getNegateNamespace();
    /**
     * <code>string negateNamespace = 7;</code>
     */
    com.google.protobuf.ByteString
        getNegateNamespaceBytes();

    /**
     * <code>string matchPod = 8;</code>
     */
    java.lang.String getMatchPod();
    /**
     * <code>string matchPod = 8;</code>
     */
    com.google.protobuf.ByteString
        getMatchPodBytes();

    /**
     * <code>string negatePod = 9;</code>
     */
    java.lang.String getNegatePod();
    /**
     * <code>string negatePod = 9;</code>
     */
    com.google.protobuf.ByteString
        getNegatePodBytes();
  }
  /**
   * Protobuf type {@code noderelayclient.NodeFilter}
   */
  public  static final class NodeFilter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:noderelayclient.NodeFilter)
      NodeFilterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeFilter.newBuilder() to construct.
    private NodeFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeFilter() {
      secret_ = "";
      matchMetadata_ = "";
      negateMetadata_ = "";
      matchUserdata_ = "";
      negateUserdata_ = "";
      matchNamespace_ = "";
      negateNamespace_ = "";
      matchPod_ = "";
      negatePod_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeFilter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              secret_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              matchMetadata_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              negateMetadata_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              matchUserdata_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              negateUserdata_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              matchNamespace_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              negateNamespace_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              matchPod_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              negatePod_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noderelayclient.NodeReflector.internal_static_noderelayclient_NodeFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noderelayclient.NodeReflector.internal_static_noderelayclient_NodeFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              noderelayclient.NodeReflector.NodeFilter.class, noderelayclient.NodeReflector.NodeFilter.Builder.class);
    }

    public static final int SECRET_FIELD_NUMBER = 1;
    private volatile java.lang.Object secret_;
    /**
     * <code>string secret = 1;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      }
    }
    /**
     * <code>string secret = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHMETADATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object matchMetadata_;
    /**
     * <code>string matchMetadata = 2;</code>
     */
    public java.lang.String getMatchMetadata() {
      java.lang.Object ref = matchMetadata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matchMetadata_ = s;
        return s;
      }
    }
    /**
     * <code>string matchMetadata = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMatchMetadataBytes() {
      java.lang.Object ref = matchMetadata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matchMetadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATEMETADATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object negateMetadata_;
    /**
     * <code>string negateMetadata = 3;</code>
     */
    public java.lang.String getNegateMetadata() {
      java.lang.Object ref = negateMetadata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negateMetadata_ = s;
        return s;
      }
    }
    /**
     * <code>string negateMetadata = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNegateMetadataBytes() {
      java.lang.Object ref = negateMetadata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negateMetadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHUSERDATA_FIELD_NUMBER = 4;
    private volatile java.lang.Object matchUserdata_;
    /**
     * <code>string matchUserdata = 4;</code>
     */
    public java.lang.String getMatchUserdata() {
      java.lang.Object ref = matchUserdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matchUserdata_ = s;
        return s;
      }
    }
    /**
     * <code>string matchUserdata = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMatchUserdataBytes() {
      java.lang.Object ref = matchUserdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matchUserdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATEUSERDATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object negateUserdata_;
    /**
     * <code>string negateUserdata = 5;</code>
     */
    public java.lang.String getNegateUserdata() {
      java.lang.Object ref = negateUserdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negateUserdata_ = s;
        return s;
      }
    }
    /**
     * <code>string negateUserdata = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNegateUserdataBytes() {
      java.lang.Object ref = negateUserdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negateUserdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHNAMESPACE_FIELD_NUMBER = 6;
    private volatile java.lang.Object matchNamespace_;
    /**
     * <code>string matchNamespace = 6;</code>
     */
    public java.lang.String getMatchNamespace() {
      java.lang.Object ref = matchNamespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matchNamespace_ = s;
        return s;
      }
    }
    /**
     * <code>string matchNamespace = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMatchNamespaceBytes() {
      java.lang.Object ref = matchNamespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matchNamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATENAMESPACE_FIELD_NUMBER = 7;
    private volatile java.lang.Object negateNamespace_;
    /**
     * <code>string negateNamespace = 7;</code>
     */
    public java.lang.String getNegateNamespace() {
      java.lang.Object ref = negateNamespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negateNamespace_ = s;
        return s;
      }
    }
    /**
     * <code>string negateNamespace = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNegateNamespaceBytes() {
      java.lang.Object ref = negateNamespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negateNamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHPOD_FIELD_NUMBER = 8;
    private volatile java.lang.Object matchPod_;
    /**
     * <code>string matchPod = 8;</code>
     */
    public java.lang.String getMatchPod() {
      java.lang.Object ref = matchPod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matchPod_ = s;
        return s;
      }
    }
    /**
     * <code>string matchPod = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMatchPodBytes() {
      java.lang.Object ref = matchPod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matchPod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATEPOD_FIELD_NUMBER = 9;
    private volatile java.lang.Object negatePod_;
    /**
     * <code>string negatePod = 9;</code>
     */
    public java.lang.String getNegatePod() {
      java.lang.Object ref = negatePod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negatePod_ = s;
        return s;
      }
    }
    /**
     * <code>string negatePod = 9;</code>
     */
    public com.google.protobuf.ByteString
        getNegatePodBytes() {
      java.lang.Object ref = negatePod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negatePod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, secret_);
      }
      if (!getMatchMetadataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, matchMetadata_);
      }
      if (!getNegateMetadataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, negateMetadata_);
      }
      if (!getMatchUserdataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, matchUserdata_);
      }
      if (!getNegateUserdataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, negateUserdata_);
      }
      if (!getMatchNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, matchNamespace_);
      }
      if (!getNegateNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, negateNamespace_);
      }
      if (!getMatchPodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, matchPod_);
      }
      if (!getNegatePodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, negatePod_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, secret_);
      }
      if (!getMatchMetadataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, matchMetadata_);
      }
      if (!getNegateMetadataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, negateMetadata_);
      }
      if (!getMatchUserdataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, matchUserdata_);
      }
      if (!getNegateUserdataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, negateUserdata_);
      }
      if (!getMatchNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, matchNamespace_);
      }
      if (!getNegateNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, negateNamespace_);
      }
      if (!getMatchPodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, matchPod_);
      }
      if (!getNegatePodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, negatePod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof noderelayclient.NodeReflector.NodeFilter)) {
        return super.equals(obj);
      }
      noderelayclient.NodeReflector.NodeFilter other = (noderelayclient.NodeReflector.NodeFilter) obj;

      boolean result = true;
      result = result && getSecret()
          .equals(other.getSecret());
      result = result && getMatchMetadata()
          .equals(other.getMatchMetadata());
      result = result && getNegateMetadata()
          .equals(other.getNegateMetadata());
      result = result && getMatchUserdata()
          .equals(other.getMatchUserdata());
      result = result && getNegateUserdata()
          .equals(other.getNegateUserdata());
      result = result && getMatchNamespace()
          .equals(other.getMatchNamespace());
      result = result && getNegateNamespace()
          .equals(other.getNegateNamespace());
      result = result && getMatchPod()
          .equals(other.getMatchPod());
      result = result && getNegatePod()
          .equals(other.getNegatePod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SECRET_FIELD_NUMBER;
      hash = (53 * hash) + getSecret().hashCode();
      hash = (37 * hash) + MATCHMETADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMatchMetadata().hashCode();
      hash = (37 * hash) + NEGATEMETADATA_FIELD_NUMBER;
      hash = (53 * hash) + getNegateMetadata().hashCode();
      hash = (37 * hash) + MATCHUSERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getMatchUserdata().hashCode();
      hash = (37 * hash) + NEGATEUSERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getNegateUserdata().hashCode();
      hash = (37 * hash) + MATCHNAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getMatchNamespace().hashCode();
      hash = (37 * hash) + NEGATENAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNegateNamespace().hashCode();
      hash = (37 * hash) + MATCHPOD_FIELD_NUMBER;
      hash = (53 * hash) + getMatchPod().hashCode();
      hash = (37 * hash) + NEGATEPOD_FIELD_NUMBER;
      hash = (53 * hash) + getNegatePod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelayclient.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(noderelayclient.NodeReflector.NodeFilter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code noderelayclient.NodeFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:noderelayclient.NodeFilter)
        noderelayclient.NodeReflector.NodeFilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return noderelayclient.NodeReflector.internal_static_noderelayclient_NodeFilter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return noderelayclient.NodeReflector.internal_static_noderelayclient_NodeFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                noderelayclient.NodeReflector.NodeFilter.class, noderelayclient.NodeReflector.NodeFilter.Builder.class);
      }

      // Construct using noderelayclient.NodeReflector.NodeFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        secret_ = "";

        matchMetadata_ = "";

        negateMetadata_ = "";

        matchUserdata_ = "";

        negateUserdata_ = "";

        matchNamespace_ = "";

        negateNamespace_ = "";

        matchPod_ = "";

        negatePod_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noderelayclient.NodeReflector.internal_static_noderelayclient_NodeFilter_descriptor;
      }

      @java.lang.Override
      public noderelayclient.NodeReflector.NodeFilter getDefaultInstanceForType() {
        return noderelayclient.NodeReflector.NodeFilter.getDefaultInstance();
      }

      @java.lang.Override
      public noderelayclient.NodeReflector.NodeFilter build() {
        noderelayclient.NodeReflector.NodeFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public noderelayclient.NodeReflector.NodeFilter buildPartial() {
        noderelayclient.NodeReflector.NodeFilter result = new noderelayclient.NodeReflector.NodeFilter(this);
        result.secret_ = secret_;
        result.matchMetadata_ = matchMetadata_;
        result.negateMetadata_ = negateMetadata_;
        result.matchUserdata_ = matchUserdata_;
        result.negateUserdata_ = negateUserdata_;
        result.matchNamespace_ = matchNamespace_;
        result.negateNamespace_ = negateNamespace_;
        result.matchPod_ = matchPod_;
        result.negatePod_ = negatePod_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noderelayclient.NodeReflector.NodeFilter) {
          return mergeFrom((noderelayclient.NodeReflector.NodeFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(noderelayclient.NodeReflector.NodeFilter other) {
        if (other == noderelayclient.NodeReflector.NodeFilter.getDefaultInstance()) return this;
        if (!other.getSecret().isEmpty()) {
          secret_ = other.secret_;
          onChanged();
        }
        if (!other.getMatchMetadata().isEmpty()) {
          matchMetadata_ = other.matchMetadata_;
          onChanged();
        }
        if (!other.getNegateMetadata().isEmpty()) {
          negateMetadata_ = other.negateMetadata_;
          onChanged();
        }
        if (!other.getMatchUserdata().isEmpty()) {
          matchUserdata_ = other.matchUserdata_;
          onChanged();
        }
        if (!other.getNegateUserdata().isEmpty()) {
          negateUserdata_ = other.negateUserdata_;
          onChanged();
        }
        if (!other.getMatchNamespace().isEmpty()) {
          matchNamespace_ = other.matchNamespace_;
          onChanged();
        }
        if (!other.getNegateNamespace().isEmpty()) {
          negateNamespace_ = other.negateNamespace_;
          onChanged();
        }
        if (!other.getMatchPod().isEmpty()) {
          matchPod_ = other.matchPod_;
          onChanged();
        }
        if (!other.getNegatePod().isEmpty()) {
          negatePod_ = other.negatePod_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        noderelayclient.NodeReflector.NodeFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (noderelayclient.NodeReflector.NodeFilter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object secret_ = "";
      /**
       * <code>string secret = 1;</code>
       */
      public java.lang.String getSecret() {
        java.lang.Object ref = secret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        java.lang.Object ref = secret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder clearSecret() {
        
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secret_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object matchMetadata_ = "";
      /**
       * <code>string matchMetadata = 2;</code>
       */
      public java.lang.String getMatchMetadata() {
        java.lang.Object ref = matchMetadata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matchMetadata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matchMetadata = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMatchMetadataBytes() {
        java.lang.Object ref = matchMetadata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matchMetadata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matchMetadata = 2;</code>
       */
      public Builder setMatchMetadata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matchMetadata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matchMetadata = 2;</code>
       */
      public Builder clearMatchMetadata() {
        
        matchMetadata_ = getDefaultInstance().getMatchMetadata();
        onChanged();
        return this;
      }
      /**
       * <code>string matchMetadata = 2;</code>
       */
      public Builder setMatchMetadataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matchMetadata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negateMetadata_ = "";
      /**
       * <code>string negateMetadata = 3;</code>
       */
      public java.lang.String getNegateMetadata() {
        java.lang.Object ref = negateMetadata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negateMetadata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negateMetadata = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNegateMetadataBytes() {
        java.lang.Object ref = negateMetadata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negateMetadata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negateMetadata = 3;</code>
       */
      public Builder setNegateMetadata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negateMetadata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negateMetadata = 3;</code>
       */
      public Builder clearNegateMetadata() {
        
        negateMetadata_ = getDefaultInstance().getNegateMetadata();
        onChanged();
        return this;
      }
      /**
       * <code>string negateMetadata = 3;</code>
       */
      public Builder setNegateMetadataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negateMetadata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object matchUserdata_ = "";
      /**
       * <code>string matchUserdata = 4;</code>
       */
      public java.lang.String getMatchUserdata() {
        java.lang.Object ref = matchUserdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matchUserdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matchUserdata = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMatchUserdataBytes() {
        java.lang.Object ref = matchUserdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matchUserdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matchUserdata = 4;</code>
       */
      public Builder setMatchUserdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matchUserdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matchUserdata = 4;</code>
       */
      public Builder clearMatchUserdata() {
        
        matchUserdata_ = getDefaultInstance().getMatchUserdata();
        onChanged();
        return this;
      }
      /**
       * <code>string matchUserdata = 4;</code>
       */
      public Builder setMatchUserdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matchUserdata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negateUserdata_ = "";
      /**
       * <code>string negateUserdata = 5;</code>
       */
      public java.lang.String getNegateUserdata() {
        java.lang.Object ref = negateUserdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negateUserdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negateUserdata = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNegateUserdataBytes() {
        java.lang.Object ref = negateUserdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negateUserdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negateUserdata = 5;</code>
       */
      public Builder setNegateUserdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negateUserdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negateUserdata = 5;</code>
       */
      public Builder clearNegateUserdata() {
        
        negateUserdata_ = getDefaultInstance().getNegateUserdata();
        onChanged();
        return this;
      }
      /**
       * <code>string negateUserdata = 5;</code>
       */
      public Builder setNegateUserdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negateUserdata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object matchNamespace_ = "";
      /**
       * <code>string matchNamespace = 6;</code>
       */
      public java.lang.String getMatchNamespace() {
        java.lang.Object ref = matchNamespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matchNamespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matchNamespace = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMatchNamespaceBytes() {
        java.lang.Object ref = matchNamespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matchNamespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matchNamespace = 6;</code>
       */
      public Builder setMatchNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matchNamespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matchNamespace = 6;</code>
       */
      public Builder clearMatchNamespace() {
        
        matchNamespace_ = getDefaultInstance().getMatchNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string matchNamespace = 6;</code>
       */
      public Builder setMatchNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matchNamespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negateNamespace_ = "";
      /**
       * <code>string negateNamespace = 7;</code>
       */
      public java.lang.String getNegateNamespace() {
        java.lang.Object ref = negateNamespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negateNamespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negateNamespace = 7;</code>
       */
      public com.google.protobuf.ByteString
          getNegateNamespaceBytes() {
        java.lang.Object ref = negateNamespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negateNamespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negateNamespace = 7;</code>
       */
      public Builder setNegateNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negateNamespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negateNamespace = 7;</code>
       */
      public Builder clearNegateNamespace() {
        
        negateNamespace_ = getDefaultInstance().getNegateNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string negateNamespace = 7;</code>
       */
      public Builder setNegateNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negateNamespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object matchPod_ = "";
      /**
       * <code>string matchPod = 8;</code>
       */
      public java.lang.String getMatchPod() {
        java.lang.Object ref = matchPod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matchPod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matchPod = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMatchPodBytes() {
        java.lang.Object ref = matchPod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matchPod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matchPod = 8;</code>
       */
      public Builder setMatchPod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matchPod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matchPod = 8;</code>
       */
      public Builder clearMatchPod() {
        
        matchPod_ = getDefaultInstance().getMatchPod();
        onChanged();
        return this;
      }
      /**
       * <code>string matchPod = 8;</code>
       */
      public Builder setMatchPodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matchPod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negatePod_ = "";
      /**
       * <code>string negatePod = 9;</code>
       */
      public java.lang.String getNegatePod() {
        java.lang.Object ref = negatePod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negatePod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negatePod = 9;</code>
       */
      public com.google.protobuf.ByteString
          getNegatePodBytes() {
        java.lang.Object ref = negatePod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negatePod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negatePod = 9;</code>
       */
      public Builder setNegatePod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negatePod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negatePod = 9;</code>
       */
      public Builder clearNegatePod() {
        
        negatePod_ = getDefaultInstance().getNegatePod();
        onChanged();
        return this;
      }
      /**
       * <code>string negatePod = 9;</code>
       */
      public Builder setNegatePodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negatePod_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:noderelayclient.NodeFilter)
    }

    // @@protoc_insertion_point(class_scope:noderelayclient.NodeFilter)
    private static final noderelayclient.NodeReflector.NodeFilter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new noderelayclient.NodeReflector.NodeFilter();
    }

    public static noderelayclient.NodeReflector.NodeFilter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeFilter>
        PARSER = new com.google.protobuf.AbstractParser<NodeFilter>() {
      @java.lang.Override
      public NodeFilter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeFilter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeFilter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeFilter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public noderelayclient.NodeReflector.NodeFilter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_noderelayclient_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_noderelayclient_Node_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_noderelayclient_NodeFilter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_noderelayclient_NodeFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/NodeReflector.proto\022\017no" +
      "derelayclient\"Z\n\004Node\022\016\n\006secret\030\001 \001(\t\022\020\n" +
      "\010metadata\030\002 \001(\t\022\020\n\010userdata\030\003 \001(\t\022\021\n\tnam" +
      "espace\030\004 \001(\t\022\013\n\003pod\030\005 \001(\t\"\320\001\n\nNodeFilter" +
      "\022\016\n\006secret\030\001 \001(\t\022\025\n\rmatchMetadata\030\002 \001(\t\022" +
      "\026\n\016negateMetadata\030\003 \001(\t\022\025\n\rmatchUserdata" +
      "\030\004 \001(\t\022\026\n\016negateUserdata\030\005 \001(\t\022\026\n\016matchN" +
      "amespace\030\006 \001(\t\022\027\n\017negateNamespace\030\007 \001(\t\022" +
      "\020\n\010matchPod\030\010 \001(\t\022\021\n\tnegatePod\030\t \001(\t2\367\001\n" +
      "\013NodeService\022@\n\006search\022\033.noderelayclient" +
      ".NodeFilter\032\025.noderelayclient.Node\"\0000\001\0225" +
      "\n\003get\022\025.noderelayclient.Node\032\025.noderelay" +
      "client.Node\"\000\0225\n\003put\022\025.noderelayclient.N" +
      "ode\032\025.noderelayclient.Node\"\000\0228\n\006delete\022\025" +
      ".noderelayclient.Node\032\025.noderelayclient." +
      "Node\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_noderelayclient_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_noderelayclient_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_noderelayclient_Node_descriptor,
        new java.lang.String[] { "Secret", "Metadata", "Userdata", "Namespace", "Pod", });
    internal_static_noderelayclient_NodeFilter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_noderelayclient_NodeFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_noderelayclient_NodeFilter_descriptor,
        new java.lang.String[] { "Secret", "MatchMetadata", "NegateMetadata", "MatchUserdata", "NegateUserdata", "MatchNamespace", "NegateNamespace", "MatchPod", "NegatePod", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
