// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/NodeReflector.proto

package noderelay.db;

public final class NodeReflector {
  private NodeReflector() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:noderelay.db.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string secret = 1;</code>
     */
    java.lang.String getSecret();
    /**
     * <code>string secret = 1;</code>
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>string metadata = 2;</code>
     */
    java.lang.String getMetadata();
    /**
     * <code>string metadata = 2;</code>
     */
    com.google.protobuf.ByteString
        getMetadataBytes();

    /**
     * <code>string userdata = 3;</code>
     */
    java.lang.String getUserdata();
    /**
     * <code>string userdata = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserdataBytes();

    /**
     * <code>string namespace = 4;</code>
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 4;</code>
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string pod = 5;</code>
     */
    java.lang.String getPod();
    /**
     * <code>string pod = 5;</code>
     */
    com.google.protobuf.ByteString
        getPodBytes();
  }
  /**
   * Protobuf type {@code noderelay.db.Node}
   */
  public  static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:noderelay.db.Node)
      NodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      secret_ = "";
      metadata_ = "";
      userdata_ = "";
      namespace_ = "";
      pod_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              secret_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              metadata_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userdata_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              pod_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noderelay.db.NodeReflector.internal_static_noderelay_db_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noderelay.db.NodeReflector.internal_static_noderelay_db_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              noderelay.db.NodeReflector.Node.class, noderelay.db.NodeReflector.Node.Builder.class);
    }

    public static final int SECRET_FIELD_NUMBER = 1;
    private volatile java.lang.Object secret_;
    /**
     * <code>string secret = 1;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      }
    }
    /**
     * <code>string secret = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METADATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object metadata_;
    /**
     * <code>string metadata = 2;</code>
     */
    public java.lang.String getMetadata() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadata_ = s;
        return s;
      }
    }
    /**
     * <code>string metadata = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMetadataBytes() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERDATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object userdata_;
    /**
     * <code>string userdata = 3;</code>
     */
    public java.lang.String getUserdata() {
      java.lang.Object ref = userdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userdata_ = s;
        return s;
      }
    }
    /**
     * <code>string userdata = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserdataBytes() {
      java.lang.Object ref = userdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAMESPACE_FIELD_NUMBER = 4;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 4;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POD_FIELD_NUMBER = 5;
    private volatile java.lang.Object pod_;
    /**
     * <code>string pod = 5;</code>
     */
    public java.lang.String getPod() {
      java.lang.Object ref = pod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pod_ = s;
        return s;
      }
    }
    /**
     * <code>string pod = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPodBytes() {
      java.lang.Object ref = pod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, secret_);
      }
      if (!getMetadataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metadata_);
      }
      if (!getUserdataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userdata_);
      }
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, namespace_);
      }
      if (!getPodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, pod_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, secret_);
      }
      if (!getMetadataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metadata_);
      }
      if (!getUserdataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userdata_);
      }
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, namespace_);
      }
      if (!getPodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, pod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof noderelay.db.NodeReflector.Node)) {
        return super.equals(obj);
      }
      noderelay.db.NodeReflector.Node other = (noderelay.db.NodeReflector.Node) obj;

      boolean result = true;
      result = result && getSecret()
          .equals(other.getSecret());
      result = result && getMetadata()
          .equals(other.getMetadata());
      result = result && getUserdata()
          .equals(other.getUserdata());
      result = result && getNamespace()
          .equals(other.getNamespace());
      result = result && getPod()
          .equals(other.getPod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SECRET_FIELD_NUMBER;
      hash = (53 * hash) + getSecret().hashCode();
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
      hash = (37 * hash) + USERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getUserdata().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + POD_FIELD_NUMBER;
      hash = (53 * hash) + getPod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static noderelay.db.NodeReflector.Node parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static noderelay.db.NodeReflector.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelay.db.NodeReflector.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(noderelay.db.NodeReflector.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code noderelay.db.Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:noderelay.db.Node)
        noderelay.db.NodeReflector.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return noderelay.db.NodeReflector.internal_static_noderelay_db_Node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return noderelay.db.NodeReflector.internal_static_noderelay_db_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                noderelay.db.NodeReflector.Node.class, noderelay.db.NodeReflector.Node.Builder.class);
      }

      // Construct using noderelay.db.NodeReflector.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        secret_ = "";

        metadata_ = "";

        userdata_ = "";

        namespace_ = "";

        pod_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noderelay.db.NodeReflector.internal_static_noderelay_db_Node_descriptor;
      }

      @java.lang.Override
      public noderelay.db.NodeReflector.Node getDefaultInstanceForType() {
        return noderelay.db.NodeReflector.Node.getDefaultInstance();
      }

      @java.lang.Override
      public noderelay.db.NodeReflector.Node build() {
        noderelay.db.NodeReflector.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public noderelay.db.NodeReflector.Node buildPartial() {
        noderelay.db.NodeReflector.Node result = new noderelay.db.NodeReflector.Node(this);
        result.secret_ = secret_;
        result.metadata_ = metadata_;
        result.userdata_ = userdata_;
        result.namespace_ = namespace_;
        result.pod_ = pod_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noderelay.db.NodeReflector.Node) {
          return mergeFrom((noderelay.db.NodeReflector.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(noderelay.db.NodeReflector.Node other) {
        if (other == noderelay.db.NodeReflector.Node.getDefaultInstance()) return this;
        if (!other.getSecret().isEmpty()) {
          secret_ = other.secret_;
          onChanged();
        }
        if (!other.getMetadata().isEmpty()) {
          metadata_ = other.metadata_;
          onChanged();
        }
        if (!other.getUserdata().isEmpty()) {
          userdata_ = other.userdata_;
          onChanged();
        }
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getPod().isEmpty()) {
          pod_ = other.pod_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        noderelay.db.NodeReflector.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (noderelay.db.NodeReflector.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object secret_ = "";
      /**
       * <code>string secret = 1;</code>
       */
      public java.lang.String getSecret() {
        java.lang.Object ref = secret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        java.lang.Object ref = secret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder clearSecret() {
        
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secret_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object metadata_ = "";
      /**
       * <code>string metadata = 2;</code>
       */
      public java.lang.String getMetadata() {
        java.lang.Object ref = metadata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metadata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMetadataBytes() {
        java.lang.Object ref = metadata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metadata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder setMetadata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metadata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder clearMetadata() {
        
        metadata_ = getDefaultInstance().getMetadata();
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder setMetadataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metadata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userdata_ = "";
      /**
       * <code>string userdata = 3;</code>
       */
      public java.lang.String getUserdata() {
        java.lang.Object ref = userdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserdataBytes() {
        java.lang.Object ref = userdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public Builder setUserdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public Builder clearUserdata() {
        
        userdata_ = getDefaultInstance().getUserdata();
        onChanged();
        return this;
      }
      /**
       * <code>string userdata = 3;</code>
       */
      public Builder setUserdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userdata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 4;</code>
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 4;</code>
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pod_ = "";
      /**
       * <code>string pod = 5;</code>
       */
      public java.lang.String getPod() {
        java.lang.Object ref = pod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pod = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPodBytes() {
        java.lang.Object ref = pod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pod = 5;</code>
       */
      public Builder setPod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pod = 5;</code>
       */
      public Builder clearPod() {
        
        pod_ = getDefaultInstance().getPod();
        onChanged();
        return this;
      }
      /**
       * <code>string pod = 5;</code>
       */
      public Builder setPodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pod_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:noderelay.db.Node)
    }

    // @@protoc_insertion_point(class_scope:noderelay.db.Node)
    private static final noderelay.db.NodeReflector.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new noderelay.db.NodeReflector.Node();
    }

    public static noderelay.db.NodeReflector.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      @java.lang.Override
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public noderelay.db.NodeReflector.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeFilterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:noderelay.db.NodeFilter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string secret = 1;</code>
     */
    java.lang.String getSecret();
    /**
     * <code>string secret = 1;</code>
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>string metadata = 2;</code>
     */
    java.lang.String getMetadata();
    /**
     * <code>string metadata = 2;</code>
     */
    com.google.protobuf.ByteString
        getMetadataBytes();

    /**
     * <code>string negatemetadata = 3;</code>
     */
    java.lang.String getNegatemetadata();
    /**
     * <code>string negatemetadata = 3;</code>
     */
    com.google.protobuf.ByteString
        getNegatemetadataBytes();

    /**
     * <code>string userdata = 4;</code>
     */
    java.lang.String getUserdata();
    /**
     * <code>string userdata = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserdataBytes();

    /**
     * <code>string negateuserdata = 5;</code>
     */
    java.lang.String getNegateuserdata();
    /**
     * <code>string negateuserdata = 5;</code>
     */
    com.google.protobuf.ByteString
        getNegateuserdataBytes();

    /**
     * <code>string namespace = 6;</code>
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 6;</code>
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string negatenamespace = 7;</code>
     */
    java.lang.String getNegatenamespace();
    /**
     * <code>string negatenamespace = 7;</code>
     */
    com.google.protobuf.ByteString
        getNegatenamespaceBytes();

    /**
     * <code>string pod = 8;</code>
     */
    java.lang.String getPod();
    /**
     * <code>string pod = 8;</code>
     */
    com.google.protobuf.ByteString
        getPodBytes();

    /**
     * <code>string negatepod = 9;</code>
     */
    java.lang.String getNegatepod();
    /**
     * <code>string negatepod = 9;</code>
     */
    com.google.protobuf.ByteString
        getNegatepodBytes();
  }
  /**
   * Protobuf type {@code noderelay.db.NodeFilter}
   */
  public  static final class NodeFilter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:noderelay.db.NodeFilter)
      NodeFilterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeFilter.newBuilder() to construct.
    private NodeFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeFilter() {
      secret_ = "";
      metadata_ = "";
      negatemetadata_ = "";
      userdata_ = "";
      negateuserdata_ = "";
      namespace_ = "";
      negatenamespace_ = "";
      pod_ = "";
      negatepod_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeFilter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              secret_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              metadata_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              negatemetadata_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userdata_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              negateuserdata_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              negatenamespace_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              pod_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              negatepod_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return noderelay.db.NodeReflector.internal_static_noderelay_db_NodeFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return noderelay.db.NodeReflector.internal_static_noderelay_db_NodeFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              noderelay.db.NodeReflector.NodeFilter.class, noderelay.db.NodeReflector.NodeFilter.Builder.class);
    }

    public static final int SECRET_FIELD_NUMBER = 1;
    private volatile java.lang.Object secret_;
    /**
     * <code>string secret = 1;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      }
    }
    /**
     * <code>string secret = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METADATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object metadata_;
    /**
     * <code>string metadata = 2;</code>
     */
    public java.lang.String getMetadata() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadata_ = s;
        return s;
      }
    }
    /**
     * <code>string metadata = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMetadataBytes() {
      java.lang.Object ref = metadata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATEMETADATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object negatemetadata_;
    /**
     * <code>string negatemetadata = 3;</code>
     */
    public java.lang.String getNegatemetadata() {
      java.lang.Object ref = negatemetadata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negatemetadata_ = s;
        return s;
      }
    }
    /**
     * <code>string negatemetadata = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNegatemetadataBytes() {
      java.lang.Object ref = negatemetadata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negatemetadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERDATA_FIELD_NUMBER = 4;
    private volatile java.lang.Object userdata_;
    /**
     * <code>string userdata = 4;</code>
     */
    public java.lang.String getUserdata() {
      java.lang.Object ref = userdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userdata_ = s;
        return s;
      }
    }
    /**
     * <code>string userdata = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserdataBytes() {
      java.lang.Object ref = userdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATEUSERDATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object negateuserdata_;
    /**
     * <code>string negateuserdata = 5;</code>
     */
    public java.lang.String getNegateuserdata() {
      java.lang.Object ref = negateuserdata_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negateuserdata_ = s;
        return s;
      }
    }
    /**
     * <code>string negateuserdata = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNegateuserdataBytes() {
      java.lang.Object ref = negateuserdata_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negateuserdata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAMESPACE_FIELD_NUMBER = 6;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 6;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATENAMESPACE_FIELD_NUMBER = 7;
    private volatile java.lang.Object negatenamespace_;
    /**
     * <code>string negatenamespace = 7;</code>
     */
    public java.lang.String getNegatenamespace() {
      java.lang.Object ref = negatenamespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negatenamespace_ = s;
        return s;
      }
    }
    /**
     * <code>string negatenamespace = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNegatenamespaceBytes() {
      java.lang.Object ref = negatenamespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negatenamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POD_FIELD_NUMBER = 8;
    private volatile java.lang.Object pod_;
    /**
     * <code>string pod = 8;</code>
     */
    public java.lang.String getPod() {
      java.lang.Object ref = pod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pod_ = s;
        return s;
      }
    }
    /**
     * <code>string pod = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPodBytes() {
      java.lang.Object ref = pod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEGATEPOD_FIELD_NUMBER = 9;
    private volatile java.lang.Object negatepod_;
    /**
     * <code>string negatepod = 9;</code>
     */
    public java.lang.String getNegatepod() {
      java.lang.Object ref = negatepod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negatepod_ = s;
        return s;
      }
    }
    /**
     * <code>string negatepod = 9;</code>
     */
    public com.google.protobuf.ByteString
        getNegatepodBytes() {
      java.lang.Object ref = negatepod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negatepod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, secret_);
      }
      if (!getMetadataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metadata_);
      }
      if (!getNegatemetadataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, negatemetadata_);
      }
      if (!getUserdataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userdata_);
      }
      if (!getNegateuserdataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, negateuserdata_);
      }
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, namespace_);
      }
      if (!getNegatenamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, negatenamespace_);
      }
      if (!getPodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pod_);
      }
      if (!getNegatepodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, negatepod_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, secret_);
      }
      if (!getMetadataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metadata_);
      }
      if (!getNegatemetadataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, negatemetadata_);
      }
      if (!getUserdataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userdata_);
      }
      if (!getNegateuserdataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, negateuserdata_);
      }
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, namespace_);
      }
      if (!getNegatenamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, negatenamespace_);
      }
      if (!getPodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pod_);
      }
      if (!getNegatepodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, negatepod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof noderelay.db.NodeReflector.NodeFilter)) {
        return super.equals(obj);
      }
      noderelay.db.NodeReflector.NodeFilter other = (noderelay.db.NodeReflector.NodeFilter) obj;

      boolean result = true;
      result = result && getSecret()
          .equals(other.getSecret());
      result = result && getMetadata()
          .equals(other.getMetadata());
      result = result && getNegatemetadata()
          .equals(other.getNegatemetadata());
      result = result && getUserdata()
          .equals(other.getUserdata());
      result = result && getNegateuserdata()
          .equals(other.getNegateuserdata());
      result = result && getNamespace()
          .equals(other.getNamespace());
      result = result && getNegatenamespace()
          .equals(other.getNegatenamespace());
      result = result && getPod()
          .equals(other.getPod());
      result = result && getNegatepod()
          .equals(other.getNegatepod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SECRET_FIELD_NUMBER;
      hash = (53 * hash) + getSecret().hashCode();
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
      hash = (37 * hash) + NEGATEMETADATA_FIELD_NUMBER;
      hash = (53 * hash) + getNegatemetadata().hashCode();
      hash = (37 * hash) + USERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getUserdata().hashCode();
      hash = (37 * hash) + NEGATEUSERDATA_FIELD_NUMBER;
      hash = (53 * hash) + getNegateuserdata().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + NEGATENAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNegatenamespace().hashCode();
      hash = (37 * hash) + POD_FIELD_NUMBER;
      hash = (53 * hash) + getPod().hashCode();
      hash = (37 * hash) + NEGATEPOD_FIELD_NUMBER;
      hash = (53 * hash) + getNegatepod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static noderelay.db.NodeReflector.NodeFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(noderelay.db.NodeReflector.NodeFilter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code noderelay.db.NodeFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:noderelay.db.NodeFilter)
        noderelay.db.NodeReflector.NodeFilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return noderelay.db.NodeReflector.internal_static_noderelay_db_NodeFilter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return noderelay.db.NodeReflector.internal_static_noderelay_db_NodeFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                noderelay.db.NodeReflector.NodeFilter.class, noderelay.db.NodeReflector.NodeFilter.Builder.class);
      }

      // Construct using noderelay.db.NodeReflector.NodeFilter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        secret_ = "";

        metadata_ = "";

        negatemetadata_ = "";

        userdata_ = "";

        negateuserdata_ = "";

        namespace_ = "";

        negatenamespace_ = "";

        pod_ = "";

        negatepod_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return noderelay.db.NodeReflector.internal_static_noderelay_db_NodeFilter_descriptor;
      }

      @java.lang.Override
      public noderelay.db.NodeReflector.NodeFilter getDefaultInstanceForType() {
        return noderelay.db.NodeReflector.NodeFilter.getDefaultInstance();
      }

      @java.lang.Override
      public noderelay.db.NodeReflector.NodeFilter build() {
        noderelay.db.NodeReflector.NodeFilter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public noderelay.db.NodeReflector.NodeFilter buildPartial() {
        noderelay.db.NodeReflector.NodeFilter result = new noderelay.db.NodeReflector.NodeFilter(this);
        result.secret_ = secret_;
        result.metadata_ = metadata_;
        result.negatemetadata_ = negatemetadata_;
        result.userdata_ = userdata_;
        result.negateuserdata_ = negateuserdata_;
        result.namespace_ = namespace_;
        result.negatenamespace_ = negatenamespace_;
        result.pod_ = pod_;
        result.negatepod_ = negatepod_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof noderelay.db.NodeReflector.NodeFilter) {
          return mergeFrom((noderelay.db.NodeReflector.NodeFilter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(noderelay.db.NodeReflector.NodeFilter other) {
        if (other == noderelay.db.NodeReflector.NodeFilter.getDefaultInstance()) return this;
        if (!other.getSecret().isEmpty()) {
          secret_ = other.secret_;
          onChanged();
        }
        if (!other.getMetadata().isEmpty()) {
          metadata_ = other.metadata_;
          onChanged();
        }
        if (!other.getNegatemetadata().isEmpty()) {
          negatemetadata_ = other.negatemetadata_;
          onChanged();
        }
        if (!other.getUserdata().isEmpty()) {
          userdata_ = other.userdata_;
          onChanged();
        }
        if (!other.getNegateuserdata().isEmpty()) {
          negateuserdata_ = other.negateuserdata_;
          onChanged();
        }
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getNegatenamespace().isEmpty()) {
          negatenamespace_ = other.negatenamespace_;
          onChanged();
        }
        if (!other.getPod().isEmpty()) {
          pod_ = other.pod_;
          onChanged();
        }
        if (!other.getNegatepod().isEmpty()) {
          negatepod_ = other.negatepod_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        noderelay.db.NodeReflector.NodeFilter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (noderelay.db.NodeReflector.NodeFilter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object secret_ = "";
      /**
       * <code>string secret = 1;</code>
       */
      public java.lang.String getSecret() {
        java.lang.Object ref = secret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        java.lang.Object ref = secret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder clearSecret() {
        
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secret_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object metadata_ = "";
      /**
       * <code>string metadata = 2;</code>
       */
      public java.lang.String getMetadata() {
        java.lang.Object ref = metadata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metadata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMetadataBytes() {
        java.lang.Object ref = metadata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metadata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder setMetadata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metadata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder clearMetadata() {
        
        metadata_ = getDefaultInstance().getMetadata();
        onChanged();
        return this;
      }
      /**
       * <code>string metadata = 2;</code>
       */
      public Builder setMetadataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metadata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negatemetadata_ = "";
      /**
       * <code>string negatemetadata = 3;</code>
       */
      public java.lang.String getNegatemetadata() {
        java.lang.Object ref = negatemetadata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negatemetadata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negatemetadata = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNegatemetadataBytes() {
        java.lang.Object ref = negatemetadata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negatemetadata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negatemetadata = 3;</code>
       */
      public Builder setNegatemetadata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negatemetadata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negatemetadata = 3;</code>
       */
      public Builder clearNegatemetadata() {
        
        negatemetadata_ = getDefaultInstance().getNegatemetadata();
        onChanged();
        return this;
      }
      /**
       * <code>string negatemetadata = 3;</code>
       */
      public Builder setNegatemetadataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negatemetadata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userdata_ = "";
      /**
       * <code>string userdata = 4;</code>
       */
      public java.lang.String getUserdata() {
        java.lang.Object ref = userdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userdata = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserdataBytes() {
        java.lang.Object ref = userdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userdata = 4;</code>
       */
      public Builder setUserdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userdata = 4;</code>
       */
      public Builder clearUserdata() {
        
        userdata_ = getDefaultInstance().getUserdata();
        onChanged();
        return this;
      }
      /**
       * <code>string userdata = 4;</code>
       */
      public Builder setUserdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userdata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negateuserdata_ = "";
      /**
       * <code>string negateuserdata = 5;</code>
       */
      public java.lang.String getNegateuserdata() {
        java.lang.Object ref = negateuserdata_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negateuserdata_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negateuserdata = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNegateuserdataBytes() {
        java.lang.Object ref = negateuserdata_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negateuserdata_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negateuserdata = 5;</code>
       */
      public Builder setNegateuserdata(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negateuserdata_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negateuserdata = 5;</code>
       */
      public Builder clearNegateuserdata() {
        
        negateuserdata_ = getDefaultInstance().getNegateuserdata();
        onChanged();
        return this;
      }
      /**
       * <code>string negateuserdata = 5;</code>
       */
      public Builder setNegateuserdataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negateuserdata_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 6;</code>
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 6;</code>
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 6;</code>
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 6;</code>
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negatenamespace_ = "";
      /**
       * <code>string negatenamespace = 7;</code>
       */
      public java.lang.String getNegatenamespace() {
        java.lang.Object ref = negatenamespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negatenamespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negatenamespace = 7;</code>
       */
      public com.google.protobuf.ByteString
          getNegatenamespaceBytes() {
        java.lang.Object ref = negatenamespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negatenamespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negatenamespace = 7;</code>
       */
      public Builder setNegatenamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negatenamespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negatenamespace = 7;</code>
       */
      public Builder clearNegatenamespace() {
        
        negatenamespace_ = getDefaultInstance().getNegatenamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string negatenamespace = 7;</code>
       */
      public Builder setNegatenamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negatenamespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pod_ = "";
      /**
       * <code>string pod = 8;</code>
       */
      public java.lang.String getPod() {
        java.lang.Object ref = pod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pod = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPodBytes() {
        java.lang.Object ref = pod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pod = 8;</code>
       */
      public Builder setPod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pod = 8;</code>
       */
      public Builder clearPod() {
        
        pod_ = getDefaultInstance().getPod();
        onChanged();
        return this;
      }
      /**
       * <code>string pod = 8;</code>
       */
      public Builder setPodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object negatepod_ = "";
      /**
       * <code>string negatepod = 9;</code>
       */
      public java.lang.String getNegatepod() {
        java.lang.Object ref = negatepod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          negatepod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string negatepod = 9;</code>
       */
      public com.google.protobuf.ByteString
          getNegatepodBytes() {
        java.lang.Object ref = negatepod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          negatepod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string negatepod = 9;</code>
       */
      public Builder setNegatepod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        negatepod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string negatepod = 9;</code>
       */
      public Builder clearNegatepod() {
        
        negatepod_ = getDefaultInstance().getNegatepod();
        onChanged();
        return this;
      }
      /**
       * <code>string negatepod = 9;</code>
       */
      public Builder setNegatepodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        negatepod_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:noderelay.db.NodeFilter)
    }

    // @@protoc_insertion_point(class_scope:noderelay.db.NodeFilter)
    private static final noderelay.db.NodeReflector.NodeFilter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new noderelay.db.NodeReflector.NodeFilter();
    }

    public static noderelay.db.NodeReflector.NodeFilter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeFilter>
        PARSER = new com.google.protobuf.AbstractParser<NodeFilter>() {
      @java.lang.Override
      public NodeFilter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeFilter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeFilter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeFilter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public noderelay.db.NodeReflector.NodeFilter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_noderelay_db_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_noderelay_db_Node_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_noderelay_db_NodeFilter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_noderelay_db_NodeFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/NodeReflector.proto\022\014no" +
      "derelay.db\"Z\n\004Node\022\016\n\006secret\030\001 \001(\t\022\020\n\010me" +
      "tadata\030\002 \001(\t\022\020\n\010userdata\030\003 \001(\t\022\021\n\tnamesp" +
      "ace\030\004 \001(\t\022\013\n\003pod\030\005 \001(\t\"\274\001\n\nNodeFilter\022\016\n" +
      "\006secret\030\001 \001(\t\022\020\n\010metadata\030\002 \001(\t\022\026\n\016negat" +
      "emetadata\030\003 \001(\t\022\020\n\010userdata\030\004 \001(\t\022\026\n\016neg" +
      "ateuserdata\030\005 \001(\t\022\021\n\tnamespace\030\006 \001(\t\022\027\n\017" +
      "negatenamespace\030\007 \001(\t\022\013\n\003pod\030\010 \001(\t\022\021\n\tne" +
      "gatepod\030\t \001(\t2\337\001\n\013NodeService\022:\n\006search\022" +
      "\030.noderelay.db.NodeFilter\032\022.noderelay.db" +
      ".Node\"\0000\001\022/\n\003get\022\022.noderelay.db.Node\032\022.n" +
      "oderelay.db.Node\"\000\022/\n\003put\022\022.noderelay.db" +
      ".Node\032\022.noderelay.db.Node\"\000\0222\n\006delete\022\022." +
      "noderelay.db.Node\032\022.noderelay.db.Node\"\000b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_noderelay_db_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_noderelay_db_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_noderelay_db_Node_descriptor,
        new java.lang.String[] { "Secret", "Metadata", "Userdata", "Namespace", "Pod", });
    internal_static_noderelay_db_NodeFilter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_noderelay_db_NodeFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_noderelay_db_NodeFilter_descriptor,
        new java.lang.String[] { "Secret", "Metadata", "Negatemetadata", "Userdata", "Negateuserdata", "Namespace", "Negatenamespace", "Pod", "Negatepod", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
